#!/usr/bin/env python3
"""
NEET Syllabus Seed Data (Story 3.2)
NTA-aligned topic list for Physics, Chemistry, and Biology.
Topics are ordered by descending NTA weightage within each subject.
"""

NEET_SYLLABUS = {
    "Physics": [
        {
            "id": "phy_01",
            "subject": "Physics",
            "title": "Laws of Motion",
            "description": "Newton's laws, friction, circular motion, dynamics of rigid bodies.",
            "nta_weightage_percent": 10,
            "exam_chapter_ref": "Class 11 - Chapter 5",
            "prerequisites": [],
            "order": 1,
        },
        {
            "id": "phy_02",
            "subject": "Physics",
            "title": "Work, Energy and Power",
            "description": "Work-energy theorem, kinetic and potential energy, conservation of energy, collisions.",
            "nta_weightage_percent": 9,
            "exam_chapter_ref": "Class 11 - Chapter 6",
            "prerequisites": ["phy_01"],
            "order": 2,
        },
        {
            "id": "phy_03",
            "subject": "Physics",
            "title": "Electrostatics",
            "description": "Coulomb's law, electric field, potential, capacitance, dielectrics.",
            "nta_weightage_percent": 9,
            "exam_chapter_ref": "Class 12 - Chapter 1",
            "prerequisites": [],
            "order": 3,
        },
        {
            "id": "phy_04",
            "subject": "Physics",
            "title": "Current Electricity",
            "description": "Ohm's law, Kirchhoff's laws, Wheatstone bridge, potentiometer.",
            "nta_weightage_percent": 8,
            "exam_chapter_ref": "Class 12 - Chapter 3",
            "prerequisites": ["phy_03"],
            "order": 4,
        },
        {
            "id": "phy_05",
            "subject": "Physics",
            "title": "Optics",
            "description": "Ray optics, wave optics, diffraction, interference, polarisation.",
            "nta_weightage_percent": 8,
            "exam_chapter_ref": "Class 12 - Chapter 9-10",
            "prerequisites": [],
            "order": 5,
        },
        {
            "id": "phy_06",
            "subject": "Physics",
            "title": "Modern Physics",
            "description": "Dual nature of radiation, photoelectric effect, atomic models, nuclear physics.",
            "nta_weightage_percent": 8,
            "exam_chapter_ref": "Class 12 - Chapter 11-13",
            "prerequisites": [],
            "order": 6,
        },
        {
            "id": "phy_07",
            "subject": "Physics",
            "title": "Magnetic Effects of Current",
            "description": "Biot-Savart law, Ampere's law, moving charges in magnetic fields, galvanometer.",
            "nta_weightage_percent": 7,
            "exam_chapter_ref": "Class 12 - Chapter 4",
            "prerequisites": ["phy_04"],
            "order": 7,
        },
        {
            "id": "phy_08",
            "subject": "Physics",
            "title": "Electromagnetic Induction (EMI)",
            "description": "Faraday's law, Lenz's law, self and mutual inductance, AC generator.",
            "nta_weightage_percent": 7,
            "exam_chapter_ref": "Class 12 - Chapter 6",
            "prerequisites": ["phy_07"],
            "order": 8,
        },
        {
            "id": "phy_09",
            "subject": "Physics",
            "title": "Thermodynamics",
            "description": "Zeroth, first, second law of thermodynamics; heat engines, Carnot cycle.",
            "nta_weightage_percent": 7,
            "exam_chapter_ref": "Class 11 - Chapter 12",
            "prerequisites": [],
            "order": 9,
        },
        {
            "id": "phy_10",
            "subject": "Physics",
            "title": "Oscillations and Waves",
            "description": "Simple harmonic motion, superposition, Doppler effect.",
            "nta_weightage_percent": 6,
            "exam_chapter_ref": "Class 11 - Chapter 14-15",
            "prerequisites": [],
            "order": 10,
        },
        {
            "id": "phy_11",
            "subject": "Physics",
            "title": "Gravitation",
            "description": "Law of gravitation, gravitational potential, satellites, escape velocity.",
            "nta_weightage_percent": 5,
            "exam_chapter_ref": "Class 11 - Chapter 8",
            "prerequisites": ["phy_01"],
            "order": 11,
        },
        {
            "id": "phy_12",
            "subject": "Physics",
            "title": "Semiconductors",
            "description": "p-n junction, diode, transistor, logic gates.",
            "nta_weightage_percent": 5,
            "exam_chapter_ref": "Class 12 - Chapter 14",
            "prerequisites": [],
            "order": 12,
        },
        {
            "id": "phy_13",
            "subject": "Physics",
            "title": "Alternating Currents",
            "description": "AC circuits, LCR circuits, resonance, transformers.",
            "nta_weightage_percent": 4,
            "exam_chapter_ref": "Class 12 - Chapter 7",
            "prerequisites": ["phy_08"],
            "order": 13,
        },
        {
            "id": "phy_14",
            "subject": "Physics",
            "title": "Electromagnetic Waves",
            "description": "Maxwell's equations, spectrum of EM waves, properties.",
            "nta_weightage_percent": 4,
            "exam_chapter_ref": "Class 12 - Chapter 8",
            "prerequisites": ["phy_08"],
            "order": 14,
        },
        {
            "id": "phy_15",
            "subject": "Physics",
            "title": "Rotational Motion",
            "description": "Moment of inertia, torque, angular momentum, rolling motion.",
            "nta_weightage_percent": 4,
            "exam_chapter_ref": "Class 11 - Chapter 7",
            "prerequisites": ["phy_01"],
            "order": 15,
        },
        {
            "id": "phy_16",
            "subject": "Physics",
            "title": "Properties of Matter",
            "description": "Elasticity, viscosity, surface tension, fluid dynamics.",
            "nta_weightage_percent": 3,
            "exam_chapter_ref": "Class 11 - Chapter 9-10",
            "prerequisites": [],
            "order": 16,
        },
        {
            "id": "phy_17",
            "subject": "Physics",
            "title": "Kinetic Theory of Gases",
            "description": "Ideal gas law, RMS speed, degrees of freedom, mean free path.",
            "nta_weightage_percent": 3,
            "exam_chapter_ref": "Class 11 - Chapter 13",
            "prerequisites": ["phy_09"],
            "order": 17,
        },
        {
            "id": "phy_18",
            "subject": "Physics",
            "title": "Physical World and Measurement",
            "description": "Units and dimensions, significant figures, error analysis.",
            "nta_weightage_percent": 2,
            "exam_chapter_ref": "Class 11 - Chapter 1-2",
            "prerequisites": [],
            "order": 18,
        },
        {
            "id": "phy_19",
            "subject": "Physics",
            "title": "Kinematics",
            "description": "Motion in 1D and 2D, projectile motion, relative motion.",
            "nta_weightage_percent": 2,
            "exam_chapter_ref": "Class 11 - Chapter 3-4",
            "prerequisites": [],
            "order": 19,
        },
        {
            "id": "phy_20",
            "subject": "Physics",
            "title": "Communication Systems",
            "description": "Modulation, bandwidth, propagation of EM waves, satellite communication.",
            "nta_weightage_percent": 2,
            "exam_chapter_ref": "Class 12 - Chapter 15",
            "prerequisites": ["phy_14"],
            "order": 20,
        },
    ],
    "Chemistry": [
        {
            "id": "chem_01",
            "subject": "Chemistry",
            "title": "Organic Chemistry Principles",
            "description": "IUPAC nomenclature, reaction mechanisms, inductive and resonance effects.",
            "nta_weightage_percent": 12,
            "exam_chapter_ref": "Class 11 - Chapter 12-13",
            "prerequisites": [],
            "order": 1,
        },
        {
            "id": "chem_02",
            "subject": "Chemistry",
            "title": "Chemical Bonding and Molecular Structure",
            "description": "VSEPR theory, hybridisation, molecular orbital theory, hydrogen bonding.",
            "nta_weightage_percent": 10,
            "exam_chapter_ref": "Class 11 - Chapter 4",
            "prerequisites": [],
            "order": 2,
        },
        {
            "id": "chem_03",
            "subject": "Chemistry",
            "title": "Coordination Compounds",
            "description": "Werner's theory, IUPAC names, isomerism, crystal field theory.",
            "nta_weightage_percent": 9,
            "exam_chapter_ref": "Class 12 - Chapter 9",
            "prerequisites": ["chem_02"],
            "order": 3,
        },
        {
            "id": "chem_04",
            "subject": "Chemistry",
            "title": "Biomolecules",
            "description": "Carbohydrates, proteins, nucleic acids, vitamins, enzymes.",
            "nta_weightage_percent": 8,
            "exam_chapter_ref": "Class 12 - Chapter 14",
            "prerequisites": ["chem_01"],
            "order": 4,
        },
        {
            "id": "chem_05",
            "subject": "Chemistry",
            "title": "Chemical Thermodynamics",
            "description": "Enthalpy, entropy, Gibbs free energy, spontaneity.",
            "nta_weightage_percent": 8,
            "exam_chapter_ref": "Class 11 - Chapter 6",
            "prerequisites": [],
            "order": 5,
        },
        {
            "id": "chem_06",
            "subject": "Chemistry",
            "title": "Equilibrium",
            "description": "Le Chatelier's principle, ionic equilibrium, pH, buffers, solubility product.",
            "nta_weightage_percent": 7,
            "exam_chapter_ref": "Class 11 - Chapter 7",
            "prerequisites": ["chem_05"],
            "order": 6,
        },
        {
            "id": "chem_07",
            "subject": "Chemistry",
            "title": "Hydrocarbons",
            "description": "Alkanes, alkenes, alkynes — nomenclature, reactions, mechanisms.",
            "nta_weightage_percent": 7,
            "exam_chapter_ref": "Class 11 - Chapter 13",
            "prerequisites": ["chem_01"],
            "order": 7,
        },
        {
            "id": "chem_08",
            "subject": "Chemistry",
            "title": "Mole Concept and Stoichiometry",
            "description": "Moles, Avogadro's number, limiting reagent, yield calculations.",
            "nta_weightage_percent": 6,
            "exam_chapter_ref": "Class 11 - Chapter 1",
            "prerequisites": [],
            "order": 8,
        },
        {
            "id": "chem_09",
            "subject": "Chemistry",
            "title": "Electrochemistry",
            "description": "Electrolytic and galvanic cells, Nernst equation, Faraday's laws.",
            "nta_weightage_percent": 6,
            "exam_chapter_ref": "Class 12 - Chapter 3",
            "prerequisites": ["chem_06"],
            "order": 9,
        },
        {
            "id": "chem_10",
            "subject": "Chemistry",
            "title": "Redox Reactions",
            "description": "Oxidation state, balancing redox equations, disproportionation.",
            "nta_weightage_percent": 5,
            "exam_chapter_ref": "Class 11 - Chapter 8",
            "prerequisites": ["chem_08"],
            "order": 10,
        },
        {
            "id": "chem_11",
            "subject": "Chemistry",
            "title": "Polymers",
            "description": "Addition and condensation polymers, natural and synthetic polymers.",
            "nta_weightage_percent": 5,
            "exam_chapter_ref": "Class 12 - Chapter 15",
            "prerequisites": ["chem_01"],
            "order": 11,
        },
        {
            "id": "chem_12",
            "subject": "Chemistry",
            "title": "Chemistry in Everyday Life",
            "description": "Drugs, food preservatives, cleansing agents, dyes.",
            "nta_weightage_percent": 4,
            "exam_chapter_ref": "Class 12 - Chapter 16",
            "prerequisites": [],
            "order": 12,
        },
        {
            "id": "chem_13",
            "subject": "Chemistry",
            "title": "p-Block Elements",
            "description": "Groups 13-18 elements, oxides, halides, oxyacids.",
            "nta_weightage_percent": 4,
            "exam_chapter_ref": "Class 11-12",
            "prerequisites": ["chem_02"],
            "order": 13,
        },
        {
            "id": "chem_14",
            "subject": "Chemistry",
            "title": "d and f Block Elements",
            "description": "Transition metals, lanthanides, actinides, properties.",
            "nta_weightage_percent": 4,
            "exam_chapter_ref": "Class 12 - Chapter 8",
            "prerequisites": [],
            "order": 14,
        },
        {
            "id": "chem_15",
            "subject": "Chemistry",
            "title": "Haloalkanes and Haloarenes",
            "description": "SN1, SN2, elimination reactions, Grignard reagent.",
            "nta_weightage_percent": 3,
            "exam_chapter_ref": "Class 12 - Chapter 10",
            "prerequisites": ["chem_07"],
            "order": 15,
        },
        {
            "id": "chem_16",
            "subject": "Chemistry",
            "title": "Alcohols, Phenols and Ethers",
            "description": "Preparation and reactions of alcohols, phenols, ethers.",
            "nta_weightage_percent": 3,
            "exam_chapter_ref": "Class 12 - Chapter 11",
            "prerequisites": ["chem_15"],
            "order": 16,
        },
        {
            "id": "chem_17",
            "subject": "Chemistry",
            "title": "Aldehydes, Ketones and Carboxylic Acids",
            "description": "Nucleophilic addition, aldol condensation, Cannizzaro reaction.",
            "nta_weightage_percent": 3,
            "exam_chapter_ref": "Class 12 - Chapter 12",
            "prerequisites": ["chem_16"],
            "order": 17,
        },
        {
            "id": "chem_18",
            "subject": "Chemistry",
            "title": "Amines",
            "description": "Classification, preparation, properties, diazonium salts.",
            "nta_weightage_percent": 2,
            "exam_chapter_ref": "Class 12 - Chapter 13",
            "prerequisites": ["chem_17"],
            "order": 18,
        },
        {
            "id": "chem_19",
            "subject": "Chemistry",
            "title": "Solid State",
            "description": "Crystal systems, unit cells, defects, semiconductors in solids.",
            "nta_weightage_percent": 2,
            "exam_chapter_ref": "Class 12 - Chapter 1",
            "prerequisites": [],
            "order": 19,
        },
        {
            "id": "chem_20",
            "subject": "Chemistry",
            "title": "Chemical Kinetics",
            "description": "Rate law, order, molecularity, Arrhenius equation, catalysis.",
            "nta_weightage_percent": 2,
            "exam_chapter_ref": "Class 12 - Chapter 4",
            "prerequisites": ["chem_06"],
            "order": 20,
        },
    ],
    "Biology": [
        {
            "id": "bio_01",
            "subject": "Biology",
            "title": "Genetics and Evolution",
            "description": "Mendelian genetics, chromosomal theory, DNA replication, mutations, Darwinian evolution.",
            "nta_weightage_percent": 14,
            "exam_chapter_ref": "Class 12 - Chapter 5-7",
            "prerequisites": [],
            "order": 1,
        },
        {
            "id": "bio_02",
            "subject": "Biology",
            "title": "Human Physiology",
            "description": "Digestive, respiratory, circulatory, excretory and nervous systems.",
            "nta_weightage_percent": 12,
            "exam_chapter_ref": "Class 11 - Chapter 16-22",
            "prerequisites": [],
            "order": 2,
        },
        {
            "id": "bio_03",
            "subject": "Biology",
            "title": "Cell Biology and Cell Division",
            "description": "Cell structure, organelles, cell cycle, mitosis, meiosis.",
            "nta_weightage_percent": 10,
            "exam_chapter_ref": "Class 11 - Chapter 8-10",
            "prerequisites": [],
            "order": 3,
        },
        {
            "id": "bio_04",
            "subject": "Biology",
            "title": "Plant Physiology",
            "description": "Photosynthesis, respiration in plants, plant growth hormones, transpiration.",
            "nta_weightage_percent": 9,
            "exam_chapter_ref": "Class 11 - Chapter 11-15",
            "prerequisites": ["bio_03"],
            "order": 4,
        },
        {
            "id": "bio_05",
            "subject": "Biology",
            "title": "Reproduction",
            "description": "Sexual and asexual reproduction in plants and animals, human reproduction, reproductive health.",
            "nta_weightage_percent": 9,
            "exam_chapter_ref": "Class 12 - Chapter 1-4",
            "prerequisites": [],
            "order": 5,
        },
        {
            "id": "bio_06",
            "subject": "Biology",
            "title": "Ecology and Environment",
            "description": "Ecosystems, food chains, biogeochemical cycles, biodiversity, environmental issues.",
            "nta_weightage_percent": 8,
            "exam_chapter_ref": "Class 12 - Chapter 13-16",
            "prerequisites": [],
            "order": 6,
        },
        {
            "id": "bio_07",
            "subject": "Biology",
            "title": "Biotechnology",
            "description": "Recombinant DNA, PCR, gel electrophoresis, GMOs, applications in medicine and agriculture.",
            "nta_weightage_percent": 8,
            "exam_chapter_ref": "Class 12 - Chapter 11-12",
            "prerequisites": ["bio_01", "bio_03"],
            "order": 7,
        },
        {
            "id": "bio_08",
            "subject": "Biology",
            "title": "Diversity in Living Organisms",
            "description": "Five kingdoms, classification, binomial nomenclature, major phyla.",
            "nta_weightage_percent": 6,
            "exam_chapter_ref": "Class 11 - Chapter 1-4",
            "prerequisites": [],
            "order": 8,
        },
        {
            "id": "bio_09",
            "subject": "Biology",
            "title": "Structural Organisation in Plants and Animals",
            "description": "Morphology of root, stem, leaf, flower; animal tissues and organ systems.",
            "nta_weightage_percent": 5,
            "exam_chapter_ref": "Class 11 - Chapter 5-7",
            "prerequisites": [],
            "order": 9,
        },
        {
            "id": "bio_10",
            "subject": "Biology",
            "title": "Biomolecules",
            "description": "Carbohydrates, proteins, nucleic acids, lipids, enzymes — structure and function.",
            "nta_weightage_percent": 5,
            "exam_chapter_ref": "Class 11 - Chapter 9",
            "prerequisites": ["bio_03"],
            "order": 10,
        },
        {
            "id": "bio_11",
            "subject": "Biology",
            "title": "Molecular Basis of Inheritance",
            "description": "DNA structure, replication, transcription, translation, genetic code.",
            "nta_weightage_percent": 4,
            "exam_chapter_ref": "Class 12 - Chapter 6",
            "prerequisites": ["bio_01"],
            "order": 11,
        },
        {
            "id": "bio_12",
            "subject": "Biology",
            "title": "Human Health and Disease",
            "description": "Immunity, vaccines, pathogens — bacteria, viruses, fungi, parasites.",
            "nta_weightage_percent": 4,
            "exam_chapter_ref": "Class 12 - Chapter 8",
            "prerequisites": ["bio_02"],
            "order": 12,
        },
        {
            "id": "bio_13",
            "subject": "Biology",
            "title": "Microbes in Human Welfare",
            "description": "Beneficial microbes — fermentation, biogas, biocontrol, biofertilisers.",
            "nta_weightage_percent": 3,
            "exam_chapter_ref": "Class 12 - Chapter 10",
            "prerequisites": [],
            "order": 13,
        },
        {
            "id": "bio_14",
            "subject": "Biology",
            "title": "Strategies for Enhancement in Food Production",
            "description": "Plant breeding, tissue culture, animal husbandry, biofortification.",
            "nta_weightage_percent": 3,
            "exam_chapter_ref": "Class 12 - Chapter 9",
            "prerequisites": [],
            "order": 14,
        },
        {
            "id": "bio_15",
            "subject": "Biology",
            "title": "Photosynthesis in Higher Plants",
            "description": "Light reactions, Calvin cycle, C3 and C4 pathways, photorespiration.",
            "nta_weightage_percent": 3,
            "exam_chapter_ref": "Class 11 - Chapter 13",
            "prerequisites": ["bio_04"],
            "order": 15,
        },
        {
            "id": "bio_16",
            "subject": "Biology",
            "title": "Respiration in Plants",
            "description": "Glycolysis, Krebs cycle, oxidative phosphorylation, fermentation.",
            "nta_weightage_percent": 3,
            "exam_chapter_ref": "Class 11 - Chapter 14",
            "prerequisites": ["bio_04"],
            "order": 16,
        },
        {
            "id": "bio_17",
            "subject": "Biology",
            "title": "Locomotion and Movement",
            "description": "Muscle types, sliding filament theory, joints, skeletal system.",
            "nta_weightage_percent": 2,
            "exam_chapter_ref": "Class 11 - Chapter 20",
            "prerequisites": ["bio_02"],
            "order": 17,
        },
        {
            "id": "bio_18",
            "subject": "Biology",
            "title": "Neural Control and Coordination",
            "description": "Neuron structure, action potential, synapse, reflex arc, brain regions.",
            "nta_weightage_percent": 2,
            "exam_chapter_ref": "Class 11 - Chapter 21",
            "prerequisites": ["bio_02"],
            "order": 18,
        },
        {
            "id": "bio_19",
            "subject": "Biology",
            "title": "Chemical Coordination and Integration",
            "description": "Endocrine glands, hormones, feedback mechanisms.",
            "nta_weightage_percent": 2,
            "exam_chapter_ref": "Class 11 - Chapter 22",
            "prerequisites": ["bio_02"],
            "order": 19,
        },
        {
            "id": "bio_20",
            "subject": "Biology",
            "title": "Excretory Products and Their Elimination",
            "description": "Modes of excretion, kidney structure, urine formation, disorders.",
            "nta_weightage_percent": 2,
            "exam_chapter_ref": "Class 11 - Chapter 19",
            "prerequisites": ["bio_02"],
            "order": 20,
        },
        {
            "id": "bio_21",
            "subject": "Biology",
            "title": "Body Fluids and Circulation",
            "description": "Blood composition, heart structure, cardiac cycle, blood groups.",
            "nta_weightage_percent": 2,
            "exam_chapter_ref": "Class 11 - Chapter 18",
            "prerequisites": ["bio_02"],
            "order": 21,
        },
        {
            "id": "bio_22",
            "subject": "Biology",
            "title": "Breathing and Exchange of Gases",
            "description": "Mechanism of breathing, transport of gases, respiratory disorders.",
            "nta_weightage_percent": 2,
            "exam_chapter_ref": "Class 11 - Chapter 17",
            "prerequisites": ["bio_02"],
            "order": 22,
        },
        {
            "id": "bio_23",
            "subject": "Biology",
            "title": "Digestion and Absorption",
            "description": "GI tract, digestive enzymes, absorption of nutrients, disorders.",
            "nta_weightage_percent": 2,
            "exam_chapter_ref": "Class 11 - Chapter 16",
            "prerequisites": [],
            "order": 23,
        },
        {
            "id": "bio_24",
            "subject": "Biology",
            "title": "Transport in Plants",
            "description": "Absorption, translocation, transpiration, ascent of sap.",
            "nta_weightage_percent": 2,
            "exam_chapter_ref": "Class 11 - Chapter 11",
            "prerequisites": [],
            "order": 24,
        },
        {
            "id": "bio_25",
            "subject": "Biology",
            "title": "Mineral Nutrition",
            "description": "Essential macro and micro elements, nitrogen fixation, deficiency symptoms.",
            "nta_weightage_percent": 1,
            "exam_chapter_ref": "Class 11 - Chapter 12",
            "prerequisites": [],
            "order": 25,
        },
        {
            "id": "bio_26",
            "subject": "Biology",
            "title": "Sexual Reproduction in Flowering Plants",
            "description": "Flower structure, pollination, fertilisation, seed and fruit development.",
            "nta_weightage_percent": 1,
            "exam_chapter_ref": "Class 12 - Chapter 2",
            "prerequisites": [],
            "order": 26,
        },
        {
            "id": "bio_27",
            "subject": "Biology",
            "title": "Human Reproduction",
            "description": "Male and female reproductive systems, gametogenesis, pregnancy, parturition.",
            "nta_weightage_percent": 1,
            "exam_chapter_ref": "Class 12 - Chapter 3",
            "prerequisites": [],
            "order": 27,
        },
        {
            "id": "bio_28",
            "subject": "Biology",
            "title": "Reproductive Health",
            "description": "Contraception, STDs, assisted reproductive technologies, MTP.",
            "nta_weightage_percent": 1,
            "exam_chapter_ref": "Class 12 - Chapter 4",
            "prerequisites": ["bio_27"],
            "order": 28,
        },
        {
            "id": "bio_29",
            "subject": "Biology",
            "title": "Organisms and Populations",
            "description": "Population attributes, growth models, species interactions.",
            "nta_weightage_percent": 1,
            "exam_chapter_ref": "Class 12 - Chapter 13",
            "prerequisites": [],
            "order": 29,
        },
        {
            "id": "bio_30",
            "subject": "Biology",
            "title": "Biodiversity and Conservation",
            "description": "Types of biodiversity, hotspots, in-situ and ex-situ conservation, IUCN.",
            "nta_weightage_percent": 1,
            "exam_chapter_ref": "Class 12 - Chapter 15",
            "prerequisites": [],
            "order": 30,
        },
    ],
}


def get_neet_modules_sorted() -> list:
    """Return all NEET topics as a flat list, sorted by subject then descending weightage."""
    all_modules = []
    for subject, topics in NEET_SYLLABUS.items():
        sorted_topics = sorted(topics, key=lambda t: -t["nta_weightage_percent"])
        for i, topic in enumerate(sorted_topics):
            topic = dict(topic)
            topic["status"] = "not_started"
            all_modules.append(topic)
    return all_modules
